### ISSUE TITLE
Question: How did you generate your PDF?

### ISSUE THREAD

**Issue by johnta0** [ojroques/hugo-researcher#14]
Thanks for a nice theme!

I'd be happy if you write how to generate PDF version of resume in README. Thanks.

**Comment by ojroques** [comment]
Hello!

I generated the PDF from my browser built-in print prompt.

**Firefox**:
Print -> Save to PDF (in *Destination*) and uncheck '*Print headers and footers*'.

**Chrome**:
Print -> Save as PDF (in *Destination*) and uncheck '*Headers and footers*'.
