### ISSUE TITLE
Theme preview on About on Github gives 404

### ISSUE THREAD

**Issue by jpmvferreira** [ojroques/hugo-researcher#26]
The preview on available on [https://themes.gohugo.io/theme/hugo-researcher/](https://themes.gohugo.io/theme/hugo-researcher/) gives a 404.

**Comment by ojroques** [comment]
It looks like Hugo doesn't host theme previews anymore. I've updated the demo link on Github, it now points to my [personal website](https://oroques.dev/) which uses the theme. Thanks for pointing that out.
