### ISSUE TITLE
change the background?

### ISSUE THREAD

**Issue by zippyy** [ojroques/hugo-researcher#27]
how would i go about changing the background color for this theme?

**Comment by ojroques** [comment]
You can modify the CSS here: [assets/sass/researcher.scss](https://github.com/ojroques/hugo-researcher/blob/master/assets/sass/researcher.scss). For example by adding:
```css
background-color: lightblue;
```

to:
https://github.com/ojroques/hugo-researcher/blob/dae5f676aa1e97f33f3d0c9bf4deb4957108caaa/assets/sass/researcher.scss#L46-L50

I won't add an option to change the background color but you can fork the project if you want.
