### ISSUE TITLE
The theme is not loading. 

### ISSUE THREAD

**Issue by mahbubcseju** [ojroques/hugo-researcher#3]
I am adding this repo as submodule. Then changed the theme to researcher. But its not loading the researcher theme.

**Comment by ojroques** [comment]
- Make sure you have Hugo _extended_ installed (chech [hugo releases](https://github.com/gohugoio/hugo/releases/tag/v0.76.3))
- Go into your website's directory or create a new one with `hugo new site your-website && cd your-website`
- Run `git submodule add https://github.com/ojroques/hugo-researcher.git themes/researcher`
- Add `theme = "researcher` to your website's `config.toml`
- Then you can build the website and serve it locaaly with `hugo server`
- An exemple of a website running the theme is available [here](https://github.com/ojroques/hugo-researcher/tree/master/exampleSite): you have to place your pages in `your-website/content` and your pictures, files etc. in `your-website/static`. Then you should create your website's menu as done [here](https://github.com/ojroques/hugo-researcher/blob/5beceabfd6a64d55737b035520dc9f9ffaa5e95b/exampleSite/config.toml#L19) for instance.

**Comment by mahbubcseju** [comment]
After putting contents and static files from theme directory to root directory, it works fine now.
