### ISSUE TITLE
Example site about/_index.md overlap?

### ISSUE THREAD

**Issue by humanfactors** [ojroques/hugo-researcher#30]
Forgive me if I'm missing something, but I found the files in the example site did not produce a "complete" example.

The default `_index.md` file contains simply the text `about.md`: https://github.com/ojroques/hugo-researcher/blob/cd2233558f3ac4c552bd2d6f408c381bda26974b/exampleSite/content/_index.md?plain=1#L1

Thus, when the example site is copied over, the index page is effectively not working. The user then needs to populate the index page with the contents from the `about.md` file, update the "about" URL in the `menu.main` toml to `url = "/"`, then delete the actual `about.md` file.

If the landing page is intended to be the `about.md` file — would it be possible to make that the contents of the `_index.md` file? 

Again, this is a pretty minor issue, but I admit themes are more accessible for new users when the example site works out of the box as intended. 

Appreciate your work on this theme — I'm using it in a Hugo tutorial for researchers :)

**Comment by ojroques** [comment]
Sorry for the late response but I'm not using the theme anymore. `_index.md` was supposed to be a symlink to `about.md` but I guess when cloning the repo that symlink is lost. U've update the theme with your suggestion, thanks.
