### ISSUE TITLE
No icons spacing after I deployed the site to Netlify

### ISSUE THREAD

**Issue by levicrews** [ojroques/hugo-researcher#38]
After I deploying my site to Netlify, the padding between the icons disappears:

**Development server**
![Screenshot_2024-01-06-48_715x92](https://github.com/ojroques/hugo-researcher/assets/20674880/36b732e1-e574-4514-849a-9321a5373429)

**After deployment**
![Screenshot_2024-01-06-03_719x79](https://github.com/ojroques/hugo-researcher/assets/20674880/10cc5eb2-40ba-4fb1-a86e-2b97020c21c4)

The same kind of problem was discussed on a Hugo Discourse [thread](https://discourse.gohugo.io/t/no-icons-spacing-after-i-deployed-the-site-to-netlify/22928), but I'm a total novice with CSS/HTML, so I can't figure out how to implement the suggested answer.

I haven't changed anything about the theme, and my ``netlify.toml`` looks like this:
```
[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.65.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
```

**Comment by ojroques** [comment]
The post suggests to remove all the `--minify` options from your `netlify.toml`. You can try that :)

I'm closing the issue since it's not a problem related to the theme but comes from netlify.

**Comment by levicrews** [comment]
Thanks for your reply! I had tried that before to no avail, which is why I made the issue, but it seems that Netlify simply failed to rebuild my site that time. All working fine now. Thanks again!
