### ISSUE TITLE
Footnotes not working?

### ISSUE THREAD

**Issue by HermanThiart** [ojroques/hugo-researcher#5]
Hey.  I really like your template for its simplicity.   It seems however that footnotes internal to the MD are not working correctly?   It is generated, but when the footnote link is clicked it renders to the home page?

**Comment by ojroques** [comment]
Hello,
Yes indeed there was an issue with footnotes. It was caused by a `<base>` tag that assigned the home page as a default target for all relative links, including footnote anchors. The issue should be fixed now. Thanks for pointing it out!

**Comment by ojroques** [comment]
Note: the patch that fixes this issue may broke existing relative links. For instance if you had before:
```md
[my-link](file.pdf)
```
to serve `http://yoursite.com/file.pdf`, now you must change that link to:
```md
[my-link](/file.pdf)
```

**Comment by HermanThiart** [comment]
Hey there.   Can confirm its all working.  :-)   Once again thank you very much for this theme and very quick response.   Awsome work!!
