### ISSUE TITLE
Adding pre/post hooks to menu items

### ISSUE THREAD

**Issue by tunix** [ojroques/hugo-researcher#8]
I want to add an RSS icon (bootstrap icon) to one of my menu items using the post hook for menu items. Currently this seems not possible with the existing `header.html` file. Would you consider adding it?

Thanks for the great theme btw!

**Comment by ojroques** [comment]
Done! Thanks for the suggestion. I've also updated the example website to use an icon in the menu: https://github.com/ojroques/hugo-researcher/blob/049680a6dc2402d44fae0a1a7d601b301d2c272b/exampleSite/config.toml#L28-L30.
